# Generated by Django 5.1.3 on 2024-11-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="active",
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.BooleanField(default=True),
        ),
    ]
